### ISSUE TITLE
support only one row?

### ISSUE THREAD

**Issue by flutterdev97** [bossbeagle1509/chip_list#1]
Is chip list package support only one row or we can show the items in multiple Rows by using this package??

**Comment by bossbeagle1509** [comment]
I will add support for this within a few hours :) 

Thank you for bringing this to my attention.

**Comment by bossbeagle1509** [comment]
Hey @flutterdev97, v **0.1.1+5** now supports wrapping a `ChipList`. You can use all the standard properties of a `Wrap` widget once you enable `shouldWrap`.

Check out the example folder's `main.dart`.

**Comment by flutterdev97** [comment]
okay thanks brother
