### ISSUE TITLE
why listOfChipIndicesCurrentlySeclected is required field?

### ISSUE THREAD

**Issue by Shailendra-3Frames** [bossbeagle1509/chip_list#13]
I don't want to select any chip by default can't we make it optional?

**Comment by Shailendra-3Frames** [comment]
Also, there is a typo in `listOfChipIndicesCurrentlySeclected` it should be `listOfChipIndicesCurrentlySelected`

**Comment by bossbeagle1509** [comment]
Both of these issues have been addressed in the latest version (3.0.0), @Shailendra-3Frames !!!

Thank you so much for the suggestion, and I'm extremely sorry for the delay
