### ISSUE TITLE
inactiveBorderColorList property has no effect

### ISSUE THREAD

**Issue by michealgabriel** [bossbeagle1509/chip_list#15]
Hi there,
The inactiveBorderColorList property of the ChipList has no effect on the inactive border color. This leaves the ChipList with a default grey border.  Please kindly look into this.
Much thanks, great package btw ❤️ 

Mike

**Comment by bossbeagle1509** [comment]
Hey Michael!

Thank you for your kind words :))

Is there an example you can provide to reproduce this problem? It seems to work fine as of now

```dart
ChipList(
                listOfChipNames: _dogeNames,
                activeBgColorList: [Theme.of(context).primaryColor],
                inactiveBgColorList: const [Colors.white],
                activeTextColorList: const [Colors.white],
                inactiveTextColorList: [Theme.of(context).primaryColor],
                listOfChipIndicesCurrentlySelected: [0],
                activeBorderColorList: [Theme.of(context).primaryColor],
                inactiveBorderColorList: [Colors.brown, Colors.pink, Colors.teal],
              ),
```

Results in

<img width="347" alt="image" src="https://github.com/bossbeagle1509/chip_list/assets/69426276/e19fce49-f138-42bd-85b7-05929cc19b48">

**Comment by michealgabriel** [comment]
Thanks for the swift reply.

Interesting 🤔, perhaps I confused it's usage. I've tested the code snippet you provided and it works as expected.

But isn't there a way to set the color once for all "inactiveBorderColor". Because in my scenario I render the list of chips based on x length of data returned from api, and I do not want to create x length of inactiveBorderColors.

Thanks.

**Comment by bossbeagle1509** [comment]
You can provide a list of length 1, it'll use the colour for all chips.

For example: 

[Colors.grey]

Every inactive chip will be grey.

**Comment by michealgabriel** [comment]
Doesn't seem to work. Please check out my code snippet below. inactiveBorderColorList is set to Colors.green but result remains default grey:

                   List<String> hashtags = ['Branding', 'Life Style', 'Movies', 'Concert', 'Branding];

                    ChipList(
                      shouldWrap: true,
                      supportsMultiSelect: true,
                      showCheckmark: false,
                      listOfChipNames: hashtags,
                      scrollPhysics: const BouncingScrollPhysics(),                                                                         
                      activeBgColorList: [Colors.red.withOpacity(0.15)],                            
                      inactiveBgColorList: const [Color(0xffF7F8F9)],                                
                      listOfChipIndicesCurrentlySeclected: [2],
                      activeBorderColorList: const [Colors.transparent],
                      inactiveBorderColorList: [Colors.green],
                      activeTextColorList: [Colors.red],                                                                      
                      inactiveTextColorList: [Color(0xff556575)],
                      style: TextStyle(fontWeight: FontWeight.w400, ),
                      borderRadiiList: const [6],   
                    ),

Result:

![image](https://github.com/bossbeagle1509/chip_list/assets/99659402/0235509d-408f-42ad-8a55-a8af8b1beeee)

**Comment by bossbeagle1509** [comment]
I'll check and let you know

**Comment by michealgabriel** [comment]
Thanks 💯

**Comment by michealgabriel** [comment]
> I'll check and let you know

Hi there 👋.
Any updates on this ?

**Comment by bossbeagle1509** [comment]
Very weird...

I pasted in your code

<img width="921" alt="image" src="https://github.com/bossbeagle1509/chip_list/assets/69426276/ee5cb432-f07f-448d-b50b-7f94f03a2d6a">

and I get the expected result

<img width="569" alt="image" src="https://github.com/bossbeagle1509/chip_list/assets/69426276/0681ca1b-5627-473b-8165-73075e656e0b">

**Comment by michealgabriel** [comment]
Very weird 🤔. 
Now I'm officially out of ideas on what the issue could be. At least now I know the issue is not from the package.😅

I guess I'd run some more tests and debugging. ❤️‍🩹

Much thanks 🔥.
