### ISSUE TITLE
Custom color on activeBgColor is not working...

### ISSUE THREAD

**Issue by flutterdev97** [bossbeagle1509/chip_list#2]
When i tried to add a custom color of activeBgColor property then its not working. Its remaining all the blue.. check this please

**Comment by bossbeagle1509** [comment]
Can you provide a minimal sample to reproduce the issue ?

**Comment by flutterdev97** [comment]
> Can you provide a minimal sample to reproduce the issue ?

ChipList(
            listOfChipNames: _dogeNames,
            supportsMultiSelect: true,
            shouldWrap: true,
            activeBgColor: Colors.orange,
            inactiveBgColor: Colors.white,
            activeTextColor: Colors.white,
            inactiveTextColor: Theme.of(context).primaryColor,
            listOfChipIndicesCurrentlySeclected: [0],
          ),

**Comment by bossbeagle1509** [comment]
:) 
That is because `supportsMultiSelect` has been set to true. This means that multiple chips can be selected at once.

To prevent this simply remove that line or set it to `false`.

**Comment by flutterdev97** [comment]
> :)
> That is because `supportsMultiSelect` has been set to true. This means that multiple chips can be selected at once.
> 
> To prevent this simply remove that line or set it to `false`.

But when the user will do when he wants supportmultiple and also custom color??

**Comment by flutterdev97** [comment]
> > :)
> > That is because `supportsMultiSelect` has been set to true. This means that multiple chips can be selected at once.
> > To prevent this simply remove that line or set it to `false`.
> 
> But whet the user will do when he wants supportmultiple and also custom color??

**Comment by bossbeagle1509** [comment]
Oh ! Thank you again !

Silly of me, the value was hardcoded. It's been patched in the latest version, **0.1.2+5**.
