### ISSUE TITLE
I can't get the selected values back

### ISSUE THREAD

**Issue by Manefa** [bossbeagle1509/chip_list#3]
I can't get the selected values back when the ChipList is in supportsMultiSelect and when I use extraOnToggle to get the selected values back it cancels the supportsMultiSelect please do you have a solution?

**Comment by bossbeagle1509** [comment]
Have you tried using `listOfChipIndicesCurrentlySeclected` ? If you provide a list there, that should update with the indices. Or is it not ?

**Comment by Manefa** [comment]
I have used listOfChipIndicesCurrentlySeclected but I don't understand how it helps me to get the selected values

**Comment by bossbeagle1509** [comment]
Pass in a list that you've stored as a variable. Then that list will always have the indices that have been selected.

**Comment by Manefa** [comment]
It worked, I didn't really understand at first, thanks for your help.

**Comment by bossbeagle1509** [comment]
Tis quite alright :)

**Comment by TCVinNYC** [comment]
I'm sorry, I'm really confused on what you mean by pass in a list as a variable for this part

Could you help me out or @Manefa could you explain as well?

**Comment by bossbeagle1509** [comment]
```
// you can use this later to find out what indices are currently selected
List indices = [];

ChipList(
              listOfChipNames: _dogeNames,
              activeBgColorList: [Theme.of(context).primaryColor],
              inactiveBgColorList: [Colors.white],
              activeTextColorList: [Colors.white],
              inactiveTextColorList: [Theme.of(context).primaryColor],
              listOfChipIndicesCurrentlySeclected: indices,
              activeBorderColorList: [Theme.of(context).primaryColor],
            ),
```

Alternatively you could also use ```extraOnToggle```,  like for example maintain the indices yourself:
```
List myList = [];
extraOnToggle(int index){
    myList.add(index);
   setState((){});
```

Does this help?
