### ISSUE TITLE
allow chip text/content padding

### ISSUE THREAD

**Issue by michealgabriel** [bossbeagle1509/chip_list#6]
Hi, I'm micheal.
I have been using your package for pretty much all my projects and it's been amazing !

- I'd love it if you could allow padding for the chip texts, it's a new feature I haven't required till now.
- Thanks a lot. Much love from Nigeria

**Comment by bossbeagle1509** [comment]
Hey Michael, that's awesome! 

I'll try and push a new version today. Looks like I set a lot of parameters as final for some reason 🙄

**Comment by michealgabriel** [comment]
Wow cool, that'd be really nice.
Thanks a lot. 😎👍

**Comment by bossbeagle1509** [comment]
Done and pushed!
