### ISSUE TITLE
Disable active icon

### ISSUE THREAD

**Issue by marcio-ota** [bossbeagle1509/chip_list#7]
Can hide icons?

**Comment by KarlMathuthu** [comment]
I've been also trying to figure that out since.

**Comment by bossbeagle1509** [comment]
I don't get it... Which icons?

**Comment by KarlMathuthu** [comment]
![Screenshot 2023-11-01 164300](https://github.com/bossbeagle1509/chip_list/assets/116157611/b1a754a2-cf16-4c47-b2cc-5d1571739193)

It's only on (useMaterial3 = true).

On Line 446 Please put these two lines of code and make them custom so we can be able to control it on the package.

```
 checkmarkColor: Colors.white,
 showCheckmark: false,
```

Thanks for responding 😊

**Comment by bossbeagle1509** [comment]
Thank YOU so much for bringing this to my notice, @KarlMathuthu!! I've uploaded a new version to pub.dev with the changes made, and the relevant logs in the changelog!!

Thank you :)
