### ISSUE TITLE
Add padding on list

### ISSUE THREAD

**Issue by ChristianNagata** [bossbeagle1509/chip_list#8]
I had to do:

SingleChildScrollView(
    scrollDirection: Axis.horizontal,
    padding: const EdgeInsets.symmetric(horizontal: 24),
    child: ChipList(
        [...]
     ),
);

would be good if had a param to define that padding

**Comment by bossbeagle1509** [comment]
Hey there :)

Were you looking to make the `ChipList` have a horizontal padding as a whole?

**Comment by ChristianNagata** [comment]
Hey,

Yes, it would be exactly like the padding we have in `ListView` or `SingleChildScrollView`.

**Comment by bossbeagle1509** [comment]
Check out the `wisgetSpacing` attribute
